# Generated by Django 5.0.4 on 2024-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='facilities',
            field=models.ManyToManyField(related_name='buses', to='station.facility'),
        ),
    ]
