# Generated by Django 5.0.4 on 2024-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_remove_ticket_unique_ticket_seats_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
