# Generated by Django 5.0.4 on 2024-04-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_facility_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('seats',)},
        ),
    ]
